# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'simple_calculator.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(317, 459)
        MainWindow.setMinimumSize(QtCore.QSize(317, 459))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.displayLabelFrame = QtWidgets.QFrame(self.frame)
        self.displayLabelFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.displayLabelFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.displayLabelFrame.setObjectName("displayLabelFrame")
        self.displayLabelFrame.setStyleSheet('QFrame {background-color: #CCCCCC;}')
        self.verticalLayout = QtWidgets.QVBoxLayout(self.displayLabelFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.historyLabel = QtWidgets.QLabel(self.displayLabelFrame)
        self.historyLabel.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.historyLabel.setFont(font)
        self.historyLabel.setTextFormat(QtCore.Qt.PlainText)
        self.historyLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.historyLabel.setObjectName("historyLabel")
        self.verticalLayout.addWidget(self.historyLabel)
        self.digitLabel = QtWidgets.QLabel(self.displayLabelFrame)
        self.digitLabel.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.digitLabel.setFont(font)
        self.digitLabel.setTextFormat(QtCore.Qt.PlainText)
        self.digitLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.digitLabel.setObjectName("digitLabel")
        self.verticalLayout.addWidget(self.digitLabel)
        self.gridLayout.addWidget(self.displayLabelFrame, 0, 0, 1, 1)
        self.buttonFrame = QtWidgets.QFrame(self.frame)
        self.buttonFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buttonFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttonFrame.setObjectName("buttonFrame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.buttonFrame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.numberSeven = QtWidgets.QPushButton(self.buttonFrame)
        self.numberSeven.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.numberSeven.setFont(font)
        self.numberSeven.setObjectName("numberSeven")
        self.gridLayout_2.addWidget(self.numberSeven, 0, 0, 1, 1)
        self.numberEight = QtWidgets.QPushButton(self.buttonFrame)
        self.numberEight.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.numberEight.setFont(font)
        self.numberEight.setObjectName("numberEight")
        self.gridLayout_2.addWidget(self.numberEight, 0, 1, 1, 1)
        self.numberNine = QtWidgets.QPushButton(self.buttonFrame)
        self.numberNine.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.numberNine.setFont(font)
        self.numberNine.setObjectName("numberNine")
        self.gridLayout_2.addWidget(self.numberNine, 0, 2, 1, 1)
        self.deleteLastButton = QtWidgets.QPushButton(self.buttonFrame)
        self.deleteLastButton.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.deleteLastButton.setFont(font)
        self.deleteLastButton.setObjectName("deleteLastButton")
        self.gridLayout_2.addWidget(self.deleteLastButton, 0, 3, 1, 1)
        self.numberFour = QtWidgets.QPushButton(self.buttonFrame)
        self.numberFour.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.numberFour.setFont(font)
        self.numberFour.setObjectName("numberFour")
        self.gridLayout_2.addWidget(self.numberFour, 1, 0, 1, 1)
        self.numberFive = QtWidgets.QPushButton(self.buttonFrame)
        self.numberFive.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.numberFive.setFont(font)
        self.numberFive.setObjectName("numberFive")
        self.gridLayout_2.addWidget(self.numberFive, 1, 1, 1, 1)
        self.numberSix = QtWidgets.QPushButton(self.buttonFrame)
        self.numberSix.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.numberSix.setFont(font)
        self.numberSix.setObjectName("numberSix")
        self.gridLayout_2.addWidget(self.numberSix, 1, 2, 1, 1)
        self.divisionButton = QtWidgets.QPushButton(self.buttonFrame)
        self.divisionButton.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.divisionButton.setFont(font)
        self.divisionButton.setObjectName("divisionButton")
        self.gridLayout_2.addWidget(self.divisionButton, 1, 3, 1, 1)
        self.numberOne = QtWidgets.QPushButton(self.buttonFrame)
        self.numberOne.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.numberOne.setFont(font)
        self.numberOne.setObjectName("numberOne")
        self.gridLayout_2.addWidget(self.numberOne, 2, 0, 1, 1)
        self.numberTwo = QtWidgets.QPushButton(self.buttonFrame)
        self.numberTwo.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.numberTwo.setFont(font)
        self.numberTwo.setObjectName("numberTwo")
        self.gridLayout_2.addWidget(self.numberTwo, 2, 1, 1, 1)
        self.numberThree = QtWidgets.QPushButton(self.buttonFrame)
        self.numberThree.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.numberThree.setFont(font)
        self.numberThree.setObjectName("numberThree")
        self.gridLayout_2.addWidget(self.numberThree, 2, 2, 1, 1)
        self.multiplicationButton = QtWidgets.QPushButton(self.buttonFrame)
        self.multiplicationButton.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.multiplicationButton.setFont(font)
        self.multiplicationButton.setObjectName("multiplicationButton")
        self.gridLayout_2.addWidget(self.multiplicationButton, 2, 3, 1, 1)
        self.clearAllButton = QtWidgets.QPushButton(self.buttonFrame)
        self.clearAllButton.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.clearAllButton.setFont(font)
        self.clearAllButton.setObjectName("clearAllButton")
        self.gridLayout_2.addWidget(self.clearAllButton, 3, 0, 1, 1)
        self.numberZero = QtWidgets.QPushButton(self.buttonFrame)
        self.numberZero.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.numberZero.setFont(font)
        self.numberZero.setObjectName("numberZero")
        self.gridLayout_2.addWidget(self.numberZero, 3, 1, 1, 1)
        self.negativePositiveButton = QtWidgets.QPushButton(self.buttonFrame)
        self.negativePositiveButton.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.negativePositiveButton.setFont(font)
        self.negativePositiveButton.setObjectName("negativePositiveButton")
        self.gridLayout_2.addWidget(self.negativePositiveButton, 3, 2, 1, 1)
        self.deductionButton = QtWidgets.QPushButton(self.buttonFrame)
        self.deductionButton.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.deductionButton.setFont(font)
        self.deductionButton.setObjectName("deductionButton")
        self.gridLayout_2.addWidget(self.deductionButton, 3, 3, 1, 1)
        self.commaButton = QtWidgets.QPushButton(self.buttonFrame)
        self.commaButton.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.commaButton.setFont(font)
        self.commaButton.setObjectName("commaButton")
        self.gridLayout_2.addWidget(self.commaButton, 4, 0, 1, 1)
        self.equalsButton = QtWidgets.QPushButton(self.buttonFrame)
        self.equalsButton.setMinimumSize(QtCore.QSize(120, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.equalsButton.setFont(font)
        self.equalsButton.setObjectName("equalsButton")
        self.gridLayout_2.addWidget(self.equalsButton, 4, 1, 1, 2)
        self.additionButton = QtWidgets.QPushButton(self.buttonFrame)
        self.additionButton.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.additionButton.setFont(font)
        self.additionButton.setObjectName("additionButton")
        self.gridLayout_2.addWidget(self.additionButton, 4, 3, 1, 1)
        self.gridLayout.addWidget(self.buttonFrame, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Basic Python Calculator"))
        self.historyLabel.setText(_translate("MainWindow", ""))
        self.digitLabel.setText(_translate("MainWindow", "0"))
        self.numberSeven.setText(_translate("MainWindow", "7"))
        self.numberEight.setText(_translate("MainWindow", "8"))
        self.numberNine.setText(_translate("MainWindow", "9"))
        self.deleteLastButton.setText(_translate("MainWindow", "<x"))
        self.numberFour.setText(_translate("MainWindow", "4"))
        self.numberFive.setText(_translate("MainWindow", "5"))
        self.numberSix.setText(_translate("MainWindow", "6"))
        self.divisionButton.setText(_translate("MainWindow", "÷"))
        self.numberOne.setText(_translate("MainWindow", "1"))
        self.numberTwo.setText(_translate("MainWindow", "2"))
        self.numberThree.setText(_translate("MainWindow", "3"))
        self.multiplicationButton.setText(_translate("MainWindow", "x"))
        self.clearAllButton.setText(_translate("MainWindow", "C"))
        self.numberZero.setText(_translate("MainWindow", "0"))
        self.negativePositiveButton.setText(_translate("MainWindow", "+/-"))
        self.deductionButton.setText(_translate("MainWindow", "-"))
        self.commaButton.setText(_translate("MainWindow", "."))
        self.equalsButton.setText(_translate("MainWindow", "="))
        self.additionButton.setText(_translate("MainWindow", "+"))
